### ISSUE TITLE
Support for multiple placeholders with same content and indentations according to mode

### ISSUE THREAD

**Issue by HardGraphite** [svaante/lsp-snippet#1]
Hi, I'm trying to use this package to make TempEL work with Eglot. But I found a few problems when I use texlab (an LSP implementation for LaTeX).

The first problem is that the same placeholder appears multiple times cannot be entered simultaneously. For example, to input something like [this (from TempEL's readme)](https://github.com/minad/tempel/blob/screenshots/latex.gif), when the cursor is at `\begin{ | }`, the inputted text (`enumerate`) is expected to appear at `\end{ | }` at the same time. But it does not, and I have to input the same text twice. It seems that the placeholder are treated as two independent ones.

The second is that indentations are expanded as tabs. I suspect this is caused by an improperly implementation of LSP server because this phenomenon doesn't occurs when using clangd (an LSP implementation for C/C++). I'm not sure about this because I don't know much about LSP. But would you please try to convert tabs to indentations according to mode (like `>` in the tempo syntax)?

Thank you for your work!

**Comment by svaante** [comment]
Hey thanks for your input.

The latest two commits should have fixed your issues.
It was just as you expected it to be texlab adds a \t char to the snippet itself.

Please get back to me if the issue still prevails.

**Comment by HardGraphite** [comment]
The fix works well!

But there's still a tiny problem. Take the `\begin{...} \end{...}` snippet I mentioned last time as an example. When I'm typing at the `\begin{}`, the text can now simultaneously appear at `\end{}`. However, after I execute `tempel-next`, the cursor jumps from `\begin{}` to `\end{}`. Since the placeholders at `\begin{ | }` and `\end{ | }` are the same one, `tempel-next` should not take the cursor from `\begin{}` to `\end{}`.

![demo](https://github.com/svaante/lsp-snippet/assets/64914256/beeb877c-fed8-4f01-b280-8cfca0910656)
