### ISSUE TITLE
malformed string with gopls

### ISSUE THREAD

**Issue by ph** [svaante/lsp-snippet#2]
Hello, I've been using `lsp-snippet`  (for tempel) with rust for some time and everything seem to work fine with their LSP server. I had to edit a go project and I've decided to try it with  gopls. The server seems to produce an invalid str format for lsp-snippet.

small reproducible case

```golang
package main

import (
	"fmt"
)

func main() {


// Complete with Println
	fmt.Print 
}

```
The server return the following

```
Possible malformed snippet "Println${1:}"

```

The following added test produce the same error.
```elisp
  (should
   (equal (lsp-snippet-parse "${1:}")
          '((tabstop 1))))


```

**Comment by svaante** [comment]
Thank you for your bug report!

I definitely missed that the specification allows for empty placeholders.
Could you verify that the last commit fixed your issue?

**Comment by ph** [comment]
Thanks @svaante for the quick turn around! 

 I've tried the latest commit and it did solve the error, but I see a different behavior between rust and go.  This might be due to the empty placeholders, the LSP implementation or something else.

```rust
fn test_ok(s: String, n: usize) -> bool {
    return true;
}

fn main() {
 test_ok(s, n)
}
```

In the above the autocomplete will generate the fragment `test_ok(s, n)`, and you can navigate with keybinds between the different parameters.

If you try a similar behavior in go:

![20231002_22h26m44s_grim](https://github.com/svaante/lsp-snippet/assets/640/0efd1d1f-f673-472b-aa21-aeff1299d053)

When you autocomplete  the `test_ok` it will generate the following fragment, that doesn't contain the paremeters.

```
test_go()
```


Is this due from the empty placeholder or a misconfiguration on my side?

**Comment by svaante** [comment]
Unfortunately this is a problem/shortcoming of gols.

It sends the following snippet "test_go(${1:})" without any place holders for the input parameters.

I would recommend opening a ticket at https://github.com/golang/tools/pulls

**Comment by ph** [comment]
Sound good, I'll follow on the go tools repo. thanks for the fix!
