### ISSUE TITLE
rust-analyzer: no space after placeholder

### ISSUE THREAD

**Issue by dchinmay2** [svaante/lsp-snippet#4]
See this:
![Screenshot from 2023-12-19 at 17_47_53 149043922](https://github.com/svaante/lsp-snippet/assets/36493671/52d6e182-1ced-436d-af4e-67d597905c21)

There is supposed to be a space between the first placeholder and the equal sign, and between the second placeholder and the opening brace (yasnippet does this correctly)

Sorry if this is hard to reproduce with other servers, r-a is the only one I use which provides space-after-placeholder snippets

**Comment by svaante** [comment]
Thanks for you bug report!
Sorry for taking so long to respond. Fix is in if you are still using lsp-snippet :)

**Comment by dchinmay2** [comment]
Thanks!
