### ISSUE TITLE
LSP-mode changed the way to check for yasnippet

### ISSUE THREAD

**Issue by FrauH0lle** [svaante/lsp-snippet#6]
Since https://github.com/emacs-lsp/lsp-mode/pull/4413, lsp-mode does not check via `featurep` anymore but `(fboundp 'yas-minor-mode)`.
Thus, `lsp-snippet-tempel-lsp-mode-init` would need to provide the minor mode instead.

I have asked at lsp-mode [here](https://github.com/emacs-lsp/lsp-mode/issues/4474) if they would consider to allow other snippet expansion libraries, which would make the integration simpler.

**Comment by svaante** [comment]
Sorry for taking such a long time to respond.

I suspect that you have stopped using lsp-snippet but your issue should be fixed by commit above

**Comment by FrauH0lle** [comment]
Thanks a lot for the fix. 
I still use `lsp-snippet ` and everything is working like a charm. Great package!
By using [el-patch](https://github.com/radian-software/el-patch) I implemented fixes for this issue here and also for https://github.com/svaante/lsp-snippet/issues/5 plus a hack which uses completing-read for choices in snippets.
